/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package autonoma.casita.gui;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author marib
 */
public class Casita extends javax.swing.JFrame {

    /**
     * Creates new form DemoCasa
     */
    public Casita() {
        initComponents();
        
        this.setSize(500,500);
        this.setLocationRelativeTo(null);
    }

    
        @Override
    
    public void paint (Graphics g){
        
        g.setColor(Color.WHITE);
        
        g.setColor(new Color(173, 216, 230));
        g.fillRect(100,150 , 200, 150);
      
        
        g.setColor(new Color(255, 160, 122));
        int[] xPoints = {100, 200, 300};
        int[] yPoints = {150, 50, 150};
        g.fillPolygon(xPoints, yPoints, 3);
        
        g.setColor(new Color(205, 133, 63));
        g.fillRect(175, 220, 50, 80);
        
        
        g.setColor(new Color(255, 255, 153));
        g.fillRect(120, 170, 30, 30);
        
        g.setColor(new Color(255, 255, 153));
        g.fillRect(250, 170, 30, 30);
        
        g.setColor(Color.GREEN);
        g.fillOval(40, 180, 60,60);
        
        g.setColor(new Color(139, 69, 19));
        g.fillRect(59, 240, 20, 65);
        
        g.setColor(Color.YELLOW);
        g.fillOval(350, 30, 60, 60);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Casita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

       Casita casa = new Casita();
        casa.setVisible(true);
    
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
